# Deploy the application as a service on the Kubernetes cluster.

# Define the pod.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default
spec:
  selector:
    matchLabels:
      run: hello-app
  template:
    metadata:
      labels:
        run: hello-app
    spec:
      containers:
      - image: gcr.io/cmu-14-848/14-848-hw-02:v0.1
        imagePullPolicy: IfNotPresent
        name: hello-app
        ports:
        - containerPort: 8080
          protocol: TCP


# Define the service for the pod.
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hello-app
  type: NodePort


# Define an ingress for the service.
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  defaultBackend:
    service:
      name: hello-svc
      port:
        number: 8080
